### ISSUE TITLE
EUC_2D distances are not rounded to the nearest integer

### ISSUE THREAD

**Issue by MartinWolke** [jakobbossek/netgen#29]
[`importFromTSPlibFormat`](https://github.com/jakobbossek/netgen/blob/master/R/importFromTSPlibFormat.R) does not round `EUC_2D` distances to the nearest integer. Don't know if this is desired, but it conflicts with the documentation of [TSPLIB](http://comopt.ifi.uni-heidelberg.de/software/TSPLIB95/). In combination with [salesperson](https://github.com/jakobbossek/salesperson) this leads to the, at the first glance, rather confusing case in which Concorde does not use rounded distances, while the other solver do.

**Comment by jakobbossek** [comment]
Thanks for the report! Going to include the rounding soon.

**Comment by jakobbossek** [comment]
Distances of `EUC_2D` instances are now rounded to the nearest integer by default. Setting `round.distances = FALSE` may be used skip rounding.
