### ISSUE TITLE
Unable to use distanceMatrix in makeNetwork function

### ISSUE THREAD

**Issue by GiGoDivakar** [jakobbossek/netgen#42]
Trying to use the makeNetwork function with a custom distance matrix and a see that the distance matrix option is not coming up. Not sure if am missing something code (VRP code using custom distance matrix) below

coord_x <- c(-25,-15,-30,0,10,-35,-25,-15,0,10,20,25,35,20,-5,-20,-10,-20,-10,-5)
coord_y <- c(30,30,20,20,20,10,10,10,0,0,0,-10,-10,-20,-30,-40,-40,-60,-60,-70)
coordinates <- array(c(coord_x,coord_y),dim = c(20,2)) 
print(coordinates)
depotCoord_x <- c(-5,-30)
depotCoord_y <- c(-50,-20)
depotCoord <- array(c(depotCoord_x,depotCoord_y), dim=c(2,2))
print(depotCoord)
dm_L1 <- c(0,9999,1922.585,2106.235,1774.315,1980.036,2202.523,1715.589,1477.4,1460.256,1817.124,1777.305,1879.046,983.873,927.958,619.203,1007.701,247.87,9999,342.963,9999,983.873)
dm_L2 <- c(9999,0,1349.955,1533.605,969.156,1645.799,2086.6,818.881,940.457,1134.714,1555.013,1807.124,1939.351,0,256.976,400.797,1352.85,1009.911,9999,1329.67,9999,0)
dm_L3 <- c(1922.585,1349.955,580.518,898.878,677.092,1331.238,1593.826,560.224,969.009,1156.69,1761.139,1842.587,1855.492,9999,1236.383,1458.905,2084.15,1988.294,9999,2537.282,9999,1225.242)
dm_L4 <- c(2106.235,1533.605,255.174,543.745,449.914,1008.137,1270.725,475.614,695.616,883.297,1438.038,1519.486,1532.391,9999,1222.831,1445.353,1810.757,2019.974,9999,2518.197,9999,1296.784)
dm_L5 <- c(1774.315,969.156,575.738,894.097,618.199,1326.457,1589.045,473.225,898.451,1086.132,1756.358,1837.806,1850.711,9999,1086.669,1366.378,1889.983,1975.492,9999,2295.251,9999,983.211)
dm_L6 <- c(1980.036,1645.799,280.072,187.078,329.499,477.485,740.073,553.074,445.317,367.125,907.386,988.834,1001.739,9999,1260.056,1442.614,1334.477,1769.675,9999,2267.898,9999,1353.877)
dm_L7 <- c(2202.523,2086.6,476.194,299.89,499.019,281.697,511.578,722.594,463.421,269.53,696.643,778.091,790.996,9999,1223.704,1271.97,1150.5,1569.3,9999,2067.523,9999,1404.191)
dm_L8 <- c(1715.589,818.881,960.309,676.107,1009.736,357.756,384.331,1233.311,1125.554,927.344,827.006,847.003,926.08,9999,1940.293,2122.851,1595.572,2449.912,9999,2948.135,9999,2034.114)
dm_L9 <- c(1477.4,940.457,632.124,1006.801,510.344,1270.592,1559.796,305.05,790.596,978.277,1583.657,1781.941,1794.846,9999,835.271,1057.793,1638.584,1587.182,9999,2072.499,9999,760.46)
dm_L10 <- c(1460.256,1134.714,467.99,733.404,236.947,997.195,1286.399,0,517.199,704.88,1354.8,1508.544,1521.449,9999,723.761,946.283,1409.727,1557.537,9999,2055.76,9999,817.582)
dm_L11 <- c(1817.124,1555.013,834.001,1017.651,685.731,888.401,1110.888,627.005,388.816,368.621,732.489,984.6,1116.827,9999,591.547,635.718,779.451,933.048,9999,1431.271,9999,812.261)
dm_L12 <- c(1777.305,1807.124,975.892,865.976,827.622,788.628,850.706,907.678,530.707,415.683,447.912,700.023,832.25,9999,889.797,916.445,579.628,1213.775,9999,1711.998,9999,1110.511)
dm_L13 <- c(1879.046,1939.351,1173.539,987.765,1133.731,571.587,555.45,1357.523,847.353,652.046,0,369.395,501.622,9999,1339.642,1366.29,746.214,1451.864,9999,1852.332,9999,1560.356)
dm_L14 <- c(983.873,0,1504.228,1318.454,1382.903,902.276,793.057,1462.959,1085.988,915.536,340.022,339.761,441.502,9999,1445.078,1382.382,440.823,1146.473,9999,1546.941,9999,1665.792)
dm_L15 <- c(927.958,256.976,1514.48,1328.706,1455.841,912.528,803.309,1535.897,1158.926,988.474,396.721,350.013,451.754,9999,1518.016,1487.19,545.632,1251.281,9999,1651.749,9999,1738.73)
dm_L16 <- c(619.203,400.797,1490.986,1489.514,1342.716,1225.835,1116.617,1373.771,1045.801,922.664,629.297,663.32,765.062,9999,1280.05,1057.84,116.282,821.931,9999,1222.399,9999,1456.963)
dm_L17 <- c(1007.701,1352.85,1333.334,1516.984,1185.064,1390.785,1613.272,1126.338,888.149,871.005,1227.873,1389.885,1491.626,9999,561.52,339.31,620.281,412.448,9999,910.671,9999,738.433)
dm_L18 <- c(247.87,1009.911,1852.242,2035.892,1397.011,1909.693,2132.18,1246.736,1407.057,1389.913,1746.781,1878.869,1980.61,9999,522.496,296.15,1109.265,524.431,9999,759.79,9999,578.411)
dm_L19 <- c(9999,9999,1712.435,1896.085,1564.165,1769.886,1992.373,1309.103,1267.25,1250.106,1606.974,1607.85,1709.591,9999,584.118,361.372,838.236,262.994,9999,656.843,9999,792.851)
dm_L20 <- c(342.963,1329.67,2286.008,2469.658,2137.738,2343.459,2565.946,1925.744,1840.823,1823.679,2180.547,2191.159,2292.9,9999,1201.504,892.749,1421.555,624.704,9999,384.142,9999,1257.419)
dm_L21 <- c(9999,9999,2274.33,2457.98,2126.06,2331.781,2471.3,2067.334,1829.145,1812.001,2168.869,2018.004,2119.745,9999,1287.359,978.604,1248.4,582.951,9999,217.107,9999,1343.274)
dm_L22 <- c(983.873,0,2358.214,2541.864,2209.944,2415.665,2472.678,2151.218,1913.029,1895.885,1985.358,2019.382,2121.123,9999,1371.243,1062.488,1249.778,666.835,9999,134.946,9999,1427.158)

distanceMatrix <- array(c(dm_L1,dm_L2,dm_L3,dm_L4,dm_L5,dm_L6,dm_L7,
						dm_L8,dm_L9,dm_L10,dm_L11,dm_L12,dm_L13,dm_L14,
						dm_L15,dm_L16,dm_L17,dm_L18,dm_L19,dm_L20,dm_L21,dm_L22), dim=c(22,22))

x <- makeNetwork(coordinates, depot.coordinates = depotCoord, lower = -100, upper = 100)
autoplot(x)

**Comment by jakobbossek** [comment]
The `distance.matrix` argument for `makeNetwork` was added in February 2016 and is included in the current [CRAN release netgen v1.3](https://cran.r-project.org/web/packages/netgen/index.html).

``` splus
...
x = makeNetwork(coordinates, depot.coordinates = depotCoord, 
  lower = -100, upper = 100, distance.matrix = distanceMatrix)
```

If this argument is not available your netgen version is not up to date. Solution: `update.packages("netgen")`. If this does not solve your problem try to first remove the current version via `remove.packages("netgen")` and reinstall from CRAN via `install.packages("netgen")`.

If the problem still occurs: Please open a new R session, load netgen via `library(netgen)`. Next, type `sessionInfo()` and post the output here.

**Comment by GiGoDivakar** [comment]
sessioninfo():

> sessionInfo()
> R version 3.0.2 (2013-09-25)
> Platform: x86_64-w64-mingw32/x64 (64-bit)

locale:
[1] LC_COLLATE=English_India.1252  LC_CTYPE=English_India.1252
[3] LC_MONETARY=English_India.1252 LC_NUMERIC=C
[5] LC_TIME=English_India.1252

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base

other attached packages:
[1] netgen_1.0    lhs_0.10      mvtnorm_1.0-2 BBmisc_1.9    rj_1.1.3-1

loaded via a namespace (and not attached):
 [1] checkmate_1.5.2  colorspace_1.2-4 digest_0.6.3     ggplot2_1.0.1
 [5] grid_3.0.2       gtable_0.1.2     lpSolve_5.6.11   MASS_7.3-37
 [9] munsell_0.4.2    plyr_1.8.1       proto_0.3-10     Rcpp_0.11.5
[13] reshape2_1.4     rj.gd_1.1.3-1    scales_0.2.4     stringr_0.6.2
[17] tools_3.0.2

**Comment by jakobbossek** [comment]
Well, your installed version is netgen 1.0. You need >= v1.3. Thus you should follow the steps I recommended in the post before.

**Comment by GiGoDivakar** [comment]
I removed the package and reinstalled the package. Followed the steps
already,. but the version is still 1.0,. how can i force the package
version when I install the package.

Thx.

**Comment by jakobbossek** [comment]
That is strange! `install.packages` always installs the up-to-date version.
Go to the [official CRAN website](https://cran.r-project.org/web/packages/netgen/index.html), download the source or binary for your operating system and follow install from file (see e.g. [this link](http://stackoverflow.com/questions/7075709/install-binary-zipped-r-package-via-command-line) for instructions).

**Comment by GiGoDivakar** [comment]
finally got the package zip installed and the distancematrix is now
working. Thx.

I dont see how can i generate paths for the network.. let me know if there
is any sample for VRP problem. Thx.

**Comment by jakobbossek** [comment]
Well, *netgen* does not contain methods for solving VRP/TSP problems as indicated in the [Description](https://github.com/jakobbossek/netgen/blob/master/DESCRIPTION).
Have a look at the [TSP package](https://cran.r-project.org/web/packages/TSP/index.html) or my package [salesperson](https://github.com/jakobbossek/salesperson). The latter is based on netgen. However, both TSP and salesperson contain only solvers for TSP, but __no__ solvers for specific VRP problems, e.g., with time windows, depots etc.

**Comment by jakobbossek** [comment]
Closing here. Reopen if necessary.
